### PR TITLE
Beefination

### PR DESCRIPTION
**Pull request by himedlooff**
### Added
- Updated to use the originally intended super buttons.
- Updated to use more cf-core utilities, some of which allow for better
  accessibility support.
### Deprecated
- Nothing.
### Removed
- Nothing.
### Fixed
- Did some code refactoring.

### CODE REVIEW

**Comment by himedlooff** [comment]
selfie-2

**Comment by ascott1** [comment]
mmm mmm good

**Comment by himedlooff** [comment]
REVIEW MEEEEE!!

selfie-1

**Comment by ascott1** [comment]
selfie-0

**Comment by himedlooff** [comment]
Thanks!

**Pull request merged**
